### ISSUE TITLE
VisibleDeprecationWarning non integer number

### ISSUE THREAD

**Issue by Housebeer** [jdherman/stockflow#1]
When the simulation is run without the "discrete=True" option, the following depreciation warning is given. On another install with a more up to date anaconda the warning is replaced by an error.

    C:\Anaconda3\lib\site-packages\ipykernel\__main__.py:5: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future

**Comment by jdherman** [comment]
Hi @Housebeer, thanks for using this code! I have not done a good job keeping up with it in the past few years, so it hasn't been tested at all on Python 3, which I'm guessing is the problem here. I'll try to investigate sometime this week.

Just curious, have you found the code to be slow? In my experience the repeated function calls to calculate each flow individually are 4-5x slower than writing the full system of equations and passing it to the ODE solver ... which is one of the reasons I haven't kept up with it.

**Comment by jdherman** [comment]
@Housebeer ok, took me a while to get back to this, sorry for the delay.

This is actually not a Python 3 problem (although I did find some other ones while testing). If the model uses `discrete=True`, then the flow functions are allowed to include `t` as an index to an array. But for model where flows are defined as continuous functions of `t`, this should not be happening anyway.

Discrete:
```python
s.flow('P', start=None, end='Sm', f=lambda t: P[t])
```
Continuous:
```python
s.flow('P', start=None, end='Sm', f=lambda t: 5*np.sin(t))
```
I will update the note about this in the Readme, and also push fixes to other python3 stuff.
